### ISSUE TITLE
framework-patcher.sh on OSX fails with "readlink: illegal option -- f"

### ISSUE THREAD

**Issue by mathissimo** [Nanolx/NanoMod#21]
I get this error when running framework-patcher.sh. It looks like if the alias (readline=greadline) is not working. I am not a shell expert, but this might be due to sub-scripts in their own shell env (missing the alias).

My Setting:
* OSX 10.11.6
* Cloned the whole git repo
* called `framework-patcher.sh 7.1` (in repo `/`)
* used with Oneplus 3T / LineageOS

```
bash-3.2$ ./framework-patcher.sh 7.1
Cloning into 'haystack'...
remote: Counting objects: 90, done.
remote: Total 90 (delta 0), reused 0 (delta 0), pack-reused 90
Unpacking objects: 100% (90/90), done.
readlink: illegal option -- f
usage: readlink [-n] [file ...]
readlink: illegal option -- f
usage: readlink [-n] [file ...]
>>> target directory: mydevice
>>> adb pull /system/framework/framework.jar mydevice/
[100%] /system/framework/framework.jar
>>> adb pull /system/framework/framework2.jar mydevice/
adb: error: remote object '/system/framework/framework2.jar' does not exist
>>> adb pull /system/framework/core.jar mydevice/
adb: error: remote object '/system/framework/core.jar' does not exist
>>> adb pull /system/framework/core-libart.jar mydevice/
[100%] /system/framework/core-libart.jar
>>> adb pull /system/framework/core-oj.jar mydevice/
[100%] /system/framework/core-oj.jar
>>> adb pull /system/framework/ext.jar mydevice/
[100%] /system/framework/ext.jar
>>> adb pull /system/framework/services.jar mydevice/
[100%] /system/framework/services.jar
>>> adb pull /system/priv-app/Settings/Settings.apk mydevice/
[100%] /system/priv-app/Settings/Settings.apk

*** pull-fileset: success
readlink: illegal option -- f
usage: readlink [-n] [file ...]
readlink: illegal option -- f
usage: readlink [-n] [file ...]
>>> target directory: mydevice__sigspoof-hook-7.0
cp: illegal option -- t
usage: cp [-R [-H | -L | -P]] [-fi | -n] [-apvX] source_file target_file
       cp [-R [-H | -L | -P]] [-fi | -n] [-apvX] source_file ... target_directory
Failed applying sigspoof hook patch!
```

**Comment by Nanolx** [comment]
This is a bug in github.com/Lanchon/Haystack, not the framework-patcher.sh

**Comment by Nanolx** [comment]
Yes, it's that the script `patch-fileset` (and possibly others) don't support OS X. Please post your issue again over at github.com/Lanchon/Haystack.

I created a fork of Haystack which should fix it. Please test again with the lasted framework-patcher.sh (which will now download my modified Haystack version).

If it works, I'll send the fix upstream.

**Comment by Nanolx** [comment]
marking as [EXTERNAL] as it's a bug in Haystack, not NanoMod.

**Comment by mathissimo** [comment]
Sorry, problem remains.
I pulled, rm haystack/, restarted shell: Same error-message
Did I miss something?

Thanks for the quick response :)

**Comment by JonnyTech** [comment]
Use this repo: https://github.com/Nanolx/haystack

**Comment by JonnyTech** [comment]
Use this repo: https://github.com/Nanolx/haystack

**Comment by mathissimo** [comment]
@JonnyTech The Nanolx haystack repo is already linked in the current `framework-patcher.sh`.
