### ISSUE TITLE
Google Play store is crashing.

### ISSUE THREAD

**Issue by ShapeShifter499** [Nanolx/NanoMod#3]
I removed the Google play store I had installed and made sure microG was removed. I git cloned the repo then flashed a version created from the command "mod.sh zip".  Here is a logcat from the crash.

[Google_play_store_crash-logcat.txt](https://github.com/Nanolx/NanoMod/files/905334/Google_play_store_crash-logcat.txt)

**Comment by Nanolx** [comment]
Your log is exactly the same I get on my phone with DroidGuard Helper. 

In fact this belongs to Magisk issue 155, see here: https://github.com/topjohnwu/Magisk/issues/155

**Comment by Nanolx** [comment]
On your phone go to

/magisk/NanoMod/system/priv-app/Phonesky

tap on Phonesyk.apk install it and see, if it works when installed as user app.

**Comment by ShapeShifter499** [comment]
Seems to be working to the point of loading to the main screen. However I'm not able to buy any new apps, I'm only able to download free or already purchased apps. Google play crashes on app purchases after selecting the payment method.  I'll post a log about it in a few.

**Comment by Nanolx** [comment]
Try deleting your google account from Settings > Accounts and re-add it.

**Comment by ShapeShifter499** [comment]
Ok so I just got around to backing up what I wanted and wiping my phone.  The latest Play Store apk you included appears corrupted. It's not allowing me to install it as a user app with an error "App not installed. The package appears to be corrupt"

**Comment by Nanolx** [comment]
Fixed.

**Comment by ShapeShifter499** [comment]
Working now, thank you. Now gong to test in-app purchases again.

**Comment by ShapeShifter499** [comment]
I should add it's working without having to install Play store as a user app.

**Comment by Nanolx** [comment]
That's only required, when the Play Store does not work as system app because of Magisk isdue 155.

Am 15. April 2017 10:26:41 MESZ schrieb Lance <notifications@github.com>:
>I should add it's working without having to install Play store as a
>user app.
>
>-- 
>You are receiving this because you commented.
>Reply to this email directly or view it on GitHub:
>https://github.com/Nanolx/NanoMod/issues/3#issuecomment-294279880

-- 
Diese Nachricht wurde von meinem Android-Gerät mit K-9 Mail gesendet.

**Comment by ShapeShifter499** [comment]
I thought https://github.com/topjohnwu/Magisk/issues/155 was steadily reproducible.  I guess I don't really understand what triggers the problem.  

On another note I am now able to make in-app purchases. I just brought a $4.99 coin pack for Pokemon GO with my PayPal account without issue. It asked for my password as expected and processed the purchase correctly as fair as I can tell.

My system as it stands starting from a freshly wiped system.
Moto X Pure
LineageOS 14.1 Nightly 04/10/2017
Magisk 12.0
NanoMod zip created from latest github with "mod.sh zip"

NanoMod settings
```
nanomod.microg=1
nanomod.fdroid=1
nanomod.apps=1
nanomod.play=1
nanomod.reinstall=0
nanomod.overlay=1
nanomod.zelda=0
```

**Comment by ShapeShifter499** [comment]
As it stands my issue is resolved! Thank you for the help and signing of the apk.  This issue can be closed now.

I have one other question: I never signed a apk file myself before, could you please tell me what you did?

**Comment by ShapeShifter499** [comment]
Ok I see, I saw issue 155 again and installing the Play store as a user app worked.

**Comment by Nanolx** [comment]
marking as [EXTERNAL] as it's caused by Magisk itself, not NanoMod.

On a side-note: as of now the issue no longer appeared to me for Play Store but still occurs for DroidGuard with Magisk v13 beta.
